name: fit_buddyy
description: "A mobile fitness app with Firebase integration."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  provider: ^6.1.2
  pedometer: ^4.0.1
  permission_handler: ^12.0.3
  intl: ^0.20.2
  fl_chart: ^1.2.0
  shared_preferences: ^2.2.1
  flutter_foreground_task: ^9.2.2
  device_info_plus: ^13.1.0
  image_picker: ^1.0.7
  confetti: ^0.8.0
  vibration: ^3.1.8
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/app_icon.png
